# Generated by Django 4.0.2 on 2022-03-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на аватар'),
        ),
    ]
